### PR TITLE
Add two-thirds middle hotkey

### PR DESCRIPTION
**Pull request by Boris-Barboris**
https://github.com/darkstego/Mudeer/issues/12

### CODE REVIEW

**Comment by darkstego** [comment]
The suggested hotkey is already used for gapless prefix. I need to think about the shortcut structure. I would like to stick to the 8 keys (ASDFZXCV) if possible. Using the 'Shift+F' key has its merit since it is being used as an alternative whole screen option. The option of 'Shift+S' makes sense too when you think about the key being used by thirds. I might have to move things around to make it work.

**Comment by Boris-Barboris** [comment]
The fact that most compositors already have a fullscreen hotkey comes to mind. Perhaps the current "Whole" hotkey is of questionable need?

**Comment by darkstego** [comment]
> The fact that most compositors already have a fullscreen hotkey comes to mind. Perhaps the current "Whole" hotkey is of questionable need?

It was actually requested, it serves two purposes. First, it provides a whole screen with gap as opposed to the maximize by compositors. Second, it allows full top half/buttom half. 

My current thinking is keeping it without a shortcut (I will need to handle the null shortcut option). With the suggestion of using "Shift+S", basically replacing centered 1/2 screen for users who want it. This will allow 4 centered options (Whole, 1/2, 1/3 - customizable, 2/3). With enough default options for 3 of the 4. Basically users can select the "Shift+S" shortcut for either 1/2 or 2/3 depending on their preference. Users are also free to add any other shortcut if they want to expand and use all 4.

**Comment by Boris-Barboris** [comment]
Sounds cool! Do I just set hotkey to empty string then? Or it will need a
deeper code modification?

пт, 14 июл. 2023 г., 09:14 darkstego ***@***.***>:

**Comment by Boris-Barboris** [comment]
Updated

**Pull request merged**
